name: Model Training and API Deployment

on:
  push:
    branches:
      - main

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/test_requirements.txt
          
      - name: Train model
        run: python bikeshare_model/train_pipeline.py
        
      - name: Run tests
        run: pytest tests/
        
      - name: Upload trained model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: bikeshare_model/trained_models/

  build-package:
    needs: train-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Download trained model
        uses: actions/download-artifact@v3
        with:
          name: trained-model
          path: bikeshare_model/trained_models/
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
          
      - name: Build package
        run: python -m build
        
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: model-package
          path: dist/

  build-and-push-docker:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download model package
        uses: actions/download-artifact@v3
        with:
          name: model-package
          path: bike_sharing_api/
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./bike_sharing_api
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME }}/bike-sharing-api:latest
          name: Model Training and API Deployment

on:
  push:
    branches:
      - main

jobs:
  train-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/test_requirements.txt
          
      - name: Train model
        run: python bikeshare_model/train_pipeline.py
        
      - name: Run tests
        run: pytest tests/
        
      - name: Upload trained model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: bikeshare_model/trained_models/

  build-package:
    needs: train-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Download trained model
        uses: actions/download-artifact@v3
        with:
          name: trained-model
          path: bikeshare_model/trained_models/
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
          
      - name: Build package
        run: python -m build
        
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: model-package
          path: dist/

  build-and-push-docker:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download model package
        uses: actions/download-artifact@v3
        with:
          name: model-package
          path: bike_sharing_api/
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./bike_sharing_api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bike-sharing-api:latest